// Role Router — point pstack skills (architect, arena, interrogate, how, why, ...) at your profiles.
//
// pstack skills pick their runners, reviewers and judges from ~/.cursor/rules/pstack-models.mdc
// ("Use the `arena runners` line ... when present"). This writes that rule with Role Router
// profiles as values and a header telling the agent to run those lanes through `role-router fan`,
// so the skills compare real model families (your Codex, Claude and OpenCode accounts) from any harness.

import os from 'node:os';
import path from 'node:path';
import { defaultFanProfiles } from './fan.mjs';

export const PSTACK_RULE = path.join(os.homedir(), '.cursor', 'rules', 'pstack-models.mdc');

/** @param {import('./config.mjs').Config} config */
export function pstackModelsRule(config) {
  const panel = defaultFanProfiles(config);
  const firstOf = (role, tier) => (config.roles[role]?.chain ?? []).find((id) => config.profiles[id]?.tier === tier)
    ?? config.roles[role]?.chain?.[0] ?? panel[0];
  const strong = firstOf('architect', 'top');
  const fast = firstOf('builder', 'lite');
  const v = (ids) => ids.map((id) => `role-router:${id}`).join(', ');
  const lines = {
    'feature, refactoring': v([fast]),
    'bug-fix': v([fast]),
    'perf-issue': v([fast]),
    hillclimb: v([fast]),
    'judgment and prose': v([strong]),
    'hardest tasks': v([strong]),
    'how explorer': v([fast]),
    'how explainer': v([strong]),
    'why investigators': v([fast]),
    'why synthesizer': v([strong]),
    'reflect tooling': v([fast]),
    'reflect judgment, divergent, synthesizer': v([strong]),
    'arena runners': v(panel),
    'arena cross-judge pool': v(panel),
    'swarm workers': v([fast]),
    'architect runners': v(panel),
    'interrogate reviewers': v(panel),
  };
  return `---
description: pstack per-role model choices (generated by role-router pstack; overrides skill defaults)
alwaysApply: true
---
# pstack model configuration, generated by \`role-router pstack\` from ~/.role-router/config.json. Re-run it after changing profiles.
# Values of the form \`role-router:<profile>\` are Role Router profiles (your Codex / Claude Code / OpenCode accounts), NOT Task model slugs.
# For such a role, do not spawn a Task subagent and do not pass it as \`model\`. Instead write the exact prompt that subagent would receive to a file and run:
#   role-router fan --profiles=<profile>[,<profile>...] --prompt-file=<file>        (add --worktree when each runner must write files)
# Panel lines (arena runners, architect runners, interrogate reviewers) run all their profiles in one fan call; single-profile lines run one.
# fan prints one answer file per profile; read every answer in full and continue the skill's workflow with them. A lane reported as waiting hit a usage limit: proceed with the others and note the dropout.
# budget: role-router profiles (effort is set by each profile's model)
${Object.entries(lines).map(([k, val]) => `${k}: ${val}`).join('\n')}
`;
}
